<!DOCTYPE html>
<html>
    <head>
        <title>umnagendra/camunda-playground - Stock Quotes Report</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            h1 {
                font-family: Arial, Helvetica, sans-serif;
                text-align: center;
            }
            table.minimalistBlack {
                font-family: Arial, Helvetica, sans-serif;
                border: 2px solid #000000;
                width: 100%;
                text-align: center;
                border-collapse: collapse;
            }
            table.minimalistBlack td, table.minimalistBlack th {
                border: 1px solid #000000;
                padding: 10px 10px;
            }
            table.minimalistBlack tbody td {
                font-size: 15px;
            }
            table.minimalistBlack tr:nth-child(even) {
                background: #D0E4F5;
            }
            table.minimalistBlack thead {
                background: #CFCFCF;
                border-bottom: 3px solid #000000;
            }
            table.minimalistBlack thead th {
                font-size: 18px;
                font-weight: bold;
                color: #000000;
                text-align: center;
            }
            table.minimalistBlack tfoot td {
                font-size: 14px;
            }
            table.minimalistBlack td:nth-child(1) {
                font-weight: bold;
                text-shadow: gray;
            }
            footer {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 12px;
                text-align: right;
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h1>Stock Quotes Report</h1>
        <table class="minimalistBlack">
            <thead>
                <tr>
                    <th>Ticker Symbol</th>
                    <th>Price (US$)</th>
                    <th>Change (%)</th>
                </tr>
            </thead>
            <tbody>
                <#list stockQuotes as stockQuote>
                <tr>
                    <td>${stockQuote.symbol}</td>
                    <td>${stockQuote.price}</td>
                    <td>${stockQuote.changePercent}</td>
                </tr>
                </#list>
            </tbody>
        </tr>
    </table>
    <footer>
        Generated by <a href="https://github.com/umnagendra/camunda-playground" target="_blank">umnagendra/camunda-playground</a>
    </footer>
    </body>
</html>